<a href="https://colab.research.google.com/github/DerinOgrenme2021/SevketOzkaya/blob/main/Odev3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Makine Öğrenmesi

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from matplotlib.colors import ListedColormap

In [10]:
iris = sns.load_dataset('iris')
iris.shape

(150, 5)

In [11]:
test_size = 0.30
seed = 7
score = 'accuracy'

In [12]:
def models(X_train, Y_train,score):
    clfs = []
    result = []
    names = []
    clfs.append(('LogReg', LogisticRegression()))
    clfs.append(('LinDiscAnly', LinearDiscriminantAnalysis()))
    clfs.append(('KNeighClss', KNeighborsClassifier()))
    clfs.append(('DecTreeClss', DecisionTreeClassifier()))
    clfs.append(('GaussNaivBayes', GaussianNB()))
    clfs.append(('SupVecMach', SVC()))
    for algo_name, clf in clfs:
        k_fold = model_selection.KFold(n_splits=10, random_state=seed)
        cv_score = model_selection.cross_val_score(clf, X_train, Y_train, cv=k_fold, scoring=score)
        result.append((algo_name,cv_score.mean(), cv_score.std()))
        names.append(algo_name)
    return (result)

In [13]:
X_all = iris.iloc[:,:4]
Y_all = iris.iloc[:,4] 

In [15]:
X_train_all, X_test_all, Y_train_all, Y_test_all = model_selection.train_test_split(X_all, Y_all, test_size=test_size, random_state=seed)
models(X_train_all, Y_train_all, score)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the n

[('LogReg', 0.9800000000000001, 0.039999999999999994),
 ('LinDiscAnly', 0.9800000000000001, 0.039999999999999994),
 ('KNeighClss', 0.9800000000000001, 0.039999999999999994),
 ('DecTreeClss', 0.9700000000000001, 0.04582575694955839),
 ('GaussNaivBayes', 0.9809090909090908, 0.03823589244511471),
 ('SupVecMach', 0.9800000000000001, 0.039999999999999994)]

In [16]:
svm = SVC()
svm.fit(X_train_all, Y_train_all)
pred = svm.predict(X_test_all)
print(accuracy_score(Y_test_all, pred))

0.8888888888888888
[[12  0  0]
 [ 0 15  1]
 [ 0  4 13]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.79      0.94      0.86        16
   virginica       0.93      0.76      0.84        17

    accuracy                           0.89        45
   macro avg       0.91      0.90      0.90        45
weighted avg       0.90      0.89      0.89        45



Derin Öğrenme

In [22]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [23]:
i = sns.load_dataset('iris')
iris = i.values

In [31]:
X = iris[1:, 0:4].astype(float)
Y = iris[1:, 4]

In [32]:
seed = 7
np.random.seed(seed)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

In [33]:
y_dummy = np_utils.to_categorical(encoded_Y)

In [34]:
def deepml_model():
    deepml = Sequential()
    deepml.add(Dense(8, input_dim=4, activation='relu'))
    deepml.add(Dense(3, activation='softmax'))
    deepml.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return deepml

In [35]:
estimate = KerasClassifier(build_fn=deepml_model, epochs=200, batch_size=5, verbose=0)

In [36]:
k_fold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [37]:
results = cross_val_score(estimate, X, y_dummy, cv=k_fold)
print("Model: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Model: 95.95% (4.45%)
